
print("АНКЕТА")
sex=input("Ваша стать")
name=input("Ваше ім'я")
lastname=input("Призвище")
age=input("Скільки років")
place=input("Де ви проживаєте(місто/село)")
hobbi=input("Яке ваше хоббі")
color=input("Який ваш улюблений колір")
knowledge=input("Де ви навчаєтесь")
zoo=input("Ваша улюблена тварина")
group=input("Ваша група відключення світла")
film=input("Улюблений фільм")
print("="*15)
print("ВАША АНКЕТА")
print("+"*15)
print(f"Стать:              {sex}")
print(f"Ім'я:               {name}")
print(f"Ім'я:               {lastname}")
print(f"Вік:                {age}")
print(f"Місто/село:         {place}")
print(f"Хоббі:              {hobbi}")
print(f"Колір:              {color}")
print(f"Навчається:         {knowledge}")
print(f"Тварина:            {zoo}")
print(f"Гупа відключення:   {group}")
print(f"Фільм:              {film}")
input("\nНатисніть Enter, щоб вийти з програми...")